services:
    mongo:
        ports:
            - 27017:27017
        image: mongo:latest
        command: --bind_ip_all
        networks:
            - app-tier
    faker:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - mongo
        networks:
            - app-tier

networks:
    app-tier:
        driver: bridge
